### ISSUE TITLE
Elo Calculator Problem

### ISSUE THREAD

**Issue by ghost** [dav1312/Chess#3]
Hi Dav

I test Elo calculator program , it work well but one thing has forgotten

imagine a person that does not have until Elo rating , the 10 first games has high factor rating 

for example , in Lichess if you won first game against 1900  , your Elo rating increase +700 , that amazing !!!!

**Comment by dav1312** [comment]
That's because Lichess doesn't use Elo, they use Glicko 2 ratings
More info here: https://lichess.org/page/rating-systems#:~:text=initial%20rating%20themselves.-,Lichess.org,-Lichess.org%20uses
